fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python3 -m unittest discover
        language: python
        pass_filenames: false
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
    -   id: autopep8
        args: [-d, --exit-code]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
