fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python3 -m unittest discover
        language: python
        pass_filenames: false
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
    -   id: autopep8
        args: [-d, --exit-code]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        args: [--disallow-untyped-defs, --show-error-codes]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
